set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports pls]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports sel]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN L2 [get_ports clk]
set_property PACKAGE_PIN G1 [get_ports rst]

set_property PACKAGE_PIN F1 [get_ports sel]
set_property PACKAGE_PIN E4 [get_ports pls]
set_property PACKAGE_PIN A7 [get_ports {seg[7]}]
set_property PACKAGE_PIN A6 [get_ports {seg[6]}]
set_property PACKAGE_PIN G5 [get_ports {seg[5]}]
set_property PACKAGE_PIN F6 [get_ports {seg[4]}]
set_property PACKAGE_PIN G7 [get_ports {seg[3]}]
set_property PACKAGE_PIN F7 [get_ports {seg[2]}]
set_property PACKAGE_PIN F8 [get_ports {seg[1]}]
set_property PACKAGE_PIN D7 [get_ports {seg[0]}]

