set_property SRC_FILE_INFO {cfile:C:/Users/user/Desktop/Vivado_test/vivado/pls_cnt_disp/pls_cnt_disp.srcs/constrs_1/new/pls_cnt_disp.xdc rfile:../../../pls_cnt_disp.srcs/constrs_1/new/pls_cnt_disp.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports clk]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports rst]
