set_property IOSTANDARD LVCMOS33 [get_ports {seg_s[0]}]
set_property PACKAGE_PIN G6 [get_ports {seg_s[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_s[1]}]
set_property PACKAGE_PIN E6 [get_ports {seg_s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_s[2]}]
set_property PACKAGE_PIN E5 [get_ports {seg_s[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_s[3]}]
set_property PACKAGE_PIN D6 [get_ports {seg_s[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_s[4]}]
set_property PACKAGE_PIN D5 [get_ports {seg_s[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_s[5]}]
set_property PACKAGE_PIN C7 [get_ports {seg_s[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_s[6]}]
set_property PACKAGE_PIN B6 [get_ports {seg_s[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_s[7]}]
set_property PACKAGE_PIN C5 [get_ports {seg_s[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_us[0]}]
set_property PACKAGE_PIN D7 [get_ports {seg_us[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_us[1]}]
set_property PACKAGE_PIN F8 [get_ports {seg_us[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_us[2]}]
set_property PACKAGE_PIN F7 [get_ports {seg_us[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_us[3]}]
set_property PACKAGE_PIN G7 [get_ports {seg_us[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_us[4]}]
set_property PACKAGE_PIN F6 [get_ports {seg_us[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_us[5]}]
set_property PACKAGE_PIN G5 [get_ports {seg_us[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_us[6]}]
set_property PACKAGE_PIN A6 [get_ports {seg_us[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_us[7]}]
set_property PACKAGE_PIN A7 [get_ports {seg_us[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports pls]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property PACKAGE_PIN L2 [get_ports clk]
set_property PACKAGE_PIN G1 [get_ports rst]
set_property PACKAGE_PIN E4 [get_ports pls]

#set_property IOSTANDARD LVCMOS18 [get_ports sel]
#set_property PACKAGE_PIN F1 [get_ports sel]


set_property IOSTANDARD LVCMOS18 [get_ports BTN]
set_property PACKAGE_PIN E4 [get_ports BTN]
